### ISSUE TITLE
The tab bar is always forced to light mode on iOS 26 when "Reduce Transparency" is on

### ISSUE THREAD

**Issue by olliFCA** [callstackincubator/react-native-bottom-tabs#433]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

On iOS 26 with the new Liquid Glass style tab bar, the background and icon appearance is always in light mode despite system setting, when the accessibility option "Reduce Transparency" is enabled in the iOS settings. When the accessibility setting is _not_ enabled, the tab bar responds to system appearance and content in the background normally. Calling `Appearance.setColorScheme('dark')` and/or using DarkTheme for the Native stack navigator has no effect on this issue. This does not seem to be a bug in iOS 26 itself, nor is the tab bar _supposed_ to be in light mode when the accessibility setting is enabled, as in Apple's own native apps the tab bar behaves normally (as shown in the example screenshot of Shortcuts below).
This issue can be replicated with the example app in this repo.

**Screenshots**
Reduce Transparency enabled and system set to dark theme, issue with the tab bar occurs.
<img width="823" height="907" alt="Reduce Transparency enabled" src="https://github.com/user-attachments/assets/65b4e194-8f85-407c-a5ca-f3fba49f69ef" />
Reduce Transparency disabled, issue does not occur.
<img width="823" height="908" alt="Reduce Transparency disabled" src="https://github.com/user-attachments/assets/4c1a0172-04f5-4135-8681-92f6d2abfea6" />
Apple's Shortcuts app for comparison. No issue with Reduce Transparency setting.
<img width="824" height="906" alt="Image" src="https://github.com/user-attachments/assets/28dc042b-7f69-44bb-b0af-ba0e49305180" />

The screenshots are from a simulator but the issue occurs on actual devices too. 

### Library version

0.11.2

### Environment info

```shell
System:
  OS: macOS 15.6.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 626.77 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.19.5
    path: /opt/homebrew/opt/node@20/bin/node
  Yarn:
    version: 4.6.0
    path: /opt/homebrew/opt/node@18/bin/yarn
  npm:
    version: 10.8.2
    path: /opt/homebrew/opt/node@20/bin/npm
  Watchman:
    version: 2025.09.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 25.0
      - iOS 26.0
      - macOS 26.0
      - tvOS 26.0
      - visionOS 26.0
      - watchOS 26.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2025.1 AI-251.26094.121.2512.13991807
  Xcode:
    version: 26.0/17A324
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.16
    path: /usr/bin/javac
  Ruby:
    version: 3.4.6
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Install the example app from this repo. 
2. (Optionally) call Appearance.setColorScheme('dark') in the `App()` function and set NavigationContainer `theme` prop to DarkTheme (imported from '@react-navigation/native').
3. In iOS Settings app, set system theme to dark and in Accessibility -> Display & Text size, enable Reduce Transparency.
4. In the example app, navigate to an example with a native tab bar.

### Reproducible sample code

```js
./apps/example/ from this repository.
```

**Comment by susanapons** [comment]
Any update here? Facing the same issue. Is allways going to light mode on transparency on

**Comment by okwasniewski** [comment]
Hey does it happen on iOS 26.1 or only on 26.0?

**Comment by Vishal-D4** [comment]
happening in 26.1 too

**Comment by olliFCA** [comment]
> Hey does it happen on iOS 26.1 or only on 26.0?

@okwasniewski 
It happened with iOS 26.1 occasionally, but not as reliably as it did with iOS 26.0. As far as I'm aware, Apple fixed similar issues in native apps in 26.1 update.
However, in the 26.2 beta, I am unable to reproduce the issue in our app that uses this library, so the issue might already be fixed via the OS update.

**Comment by bastiendmt** [comment]
Using iOS 26.2 public version, I confirm that the "flashing" is still happening

**Comment by sept-jm** [comment]
I'm having this issue on iOS 26.3. In my case it resolves after scrolling.

https://github.com/user-attachments/assets/57853755-3073-4898-aaed-0349c3e92f28

Maybe it is also worth noting that the same setup on an iOS 18.1 device has similar behavior. The color of the icons corrects itself after switching tabs.

https://github.com/user-attachments/assets/6b875684-b80d-414b-a8a0-4012a8a3d5e6

Slight aside; is there any information on how React Navigation theming interacts with this library?

**Comment by sept-jm** [comment]
In my case it seems like maybe the OS color scheme is fighting the app color scheme. I was able to fix in my Expo project by setting `"userInterfaceStyle": "automatic"` (see [here](https://docs.expo.dev/develop/user-interface/color-themes/#configuration)) in my app.json. It seems to always default to the OS color scheme first before updating from whatever is behind it (rather inconsistently).

**Comment by Yawan-1** [comment]
Still haven't fixed? Because it is still showing light bar when changing tabs but it changes to dark when Scroll or cause a redraw.

**Comment by bastiendmt** [comment]
I managed to find a workaround! 

It looks like the bottom tabs follow the phone's system color scheme. Setting `DarkTheme` on `<NavigationContainer>` alone doesn't seem to be enough.

In my case, the app only supports a dark theme, but some users have their phones configured to automatically switch between light and dark mode based on a schedule. As a result, the bottom tabs can be rendered with a light theme during the day.

The workaround is to explicitly force the app's color scheme:

```ts
Appearance.setColorScheme('dark')
```

Here is a comparison:

| without | with |
|--------|--------|
| <img width="1179" height="294" alt="Image" src="https://github.com/user-attachments/assets/ced1ed11-222a-47c5-b6c2-95ef6ba4a486" /> | <img width="1179" height="296" alt="Image" src="https://github.com/user-attachments/assets/62909940-c926-40df-b41f-62ff6271a8b9" /> |

It even works with reduced transparency ON. 
I hope this helps in fixing the bug
